




	
	
		

	
	
		

	
	
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		

	
	
		
		
		

	
	
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		

	
	
		

	
	
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		

	
	
		

	
	
		
		
		
		

	
	
		
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		
		

	
	
		
		

	
	
		
		

	
	
		
		
		

	
	
		

	
	
		
		
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="generator" content="Hugo 0.101.0">
    <meta name="generator" content="Relearn 5.18.0">
    <meta name="description" content="CC 210 Textbook">
    <meta name="author" content="Russell Feldhausen">
    <title>Python Exceptions :: CC 210 Textbook</title>
    <link href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/index.html" rel="canonical" type="text/html" title="Python Exceptions :: CC 210 Textbook">
    <link href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/index.xml" rel="alternate" type="application/rss+xml" title="Python Exceptions :: CC 210 Textbook">
    <link href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/tele.html" rel="alternate" type="text/html" title="Python Exceptions :: CC 210 Textbook">
    <link href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/embed.html" rel="alternate" type="text/html" title="Python Exceptions :: CC 210 Textbook">
    <!-- https://github.com/filamentgroup/loadCSS/blob/master/README.md#how-to-use -->
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/fontawesome-all.min.css?1691776798" rel="stylesheet" media="print" onload="this.media='all';this.onload=null;"><noscript><link href="https://ksu-cs-textbooks.github.io/cc210/css/fontawesome-all.min.css?1691776798" rel="stylesheet"></noscript>
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/nucleus.css?1691776798" rel="stylesheet">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/auto-complete.css?1691776798" rel="stylesheet" media="print" onload="this.media='all';this.onload=null;"><noscript><link href="https://ksu-cs-textbooks.github.io/cc210/css/auto-complete.css?1691776798" rel="stylesheet"></noscript>
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/perfect-scrollbar.min.css?1691776798" rel="stylesheet">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/fonts.css?1691776798" rel="stylesheet" media="print" onload="this.media='all';this.onload=null;"><noscript><link href="https://ksu-cs-textbooks.github.io/cc210/css/fonts.css?1691776798" rel="stylesheet"></noscript>
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/theme.css?1691776798" rel="stylesheet">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/theme-auto.css?1691776798" rel="stylesheet" id="variant-style">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/variant.css?1691776798" rel="stylesheet">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/print.css?1691776798" rel="stylesheet" media="print">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/format-print.css?1691776798" rel="stylesheet">
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/ie.css?1691776798" rel="stylesheet">
    <script src="https://ksu-cs-textbooks.github.io/cc210/js/url.js?1691776798"></script>
    <script src="https://ksu-cs-textbooks.github.io/cc210/js/variant.js?1691776798"></script>
    <script>
      // hack to let hugo tell us how to get to the root when using relativeURLs, it needs to be called *url= for it to do its magic:
      // https://github.com/gohugoio/hugo/blob/145b3fcce35fbac25c7033c91c1b7ae6d1179da8/transform/urlreplacers/absurlreplacer.go#L72
      window.index_js_url="https://ksu-cs-textbooks.github.io/cc210/index.search.js";
      var root_url="https://ksu-cs-textbooks.github.io/cc210/";
      var baseUri=root_url.replace(/\/$/, '');
      // translations
      window.T_Copy_to_clipboard = 'Copy to clipboard';
      window.T_Copied_to_clipboard = 'Copied to clipboard!';
      window.T_Copy_link_to_clipboard = 'Copy link to clipboard';
      window.T_Link_copied_to_clipboard = 'Copied link to clipboard!';
      window.T_No_results_found = 'No results found for \u0022{0}\u0022';
      window.T_N_results_found = '{1} results found for \u0022{0}\u0022';
      // some further base stuff
      var baseUriFull='https:\/\/ksu-cs-textbooks.github.io\/cc210/';
      window.variants && variants.init( [ 'auto', 'light-theme', 'dark-theme' ] );
    </script>
    
    <link href="https://ksu-cs-textbooks.github.io/cc210/css/custom.css?1691776798" rel="stylesheet">

  </head>
  <body class="mobile-support print disableInlineCopyToClipboard" data-url="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/index.html">
    <div id="body" class="default-animation">
      <div id="sidebar-overlay"></div>
      <div id="toc-overlay"></div>
      <nav id="topbar" class="highlightable">
        <div>
          <div id="top-tele-link">
            <a class="print-link" title='Teleprompter View' href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/tele.html">
              <i class="fas fa-tv fa-fw"></i>
            </a>
          </div>
          <div id="top-embed-link">
            <a class="print-link" title='Embeddable Version' href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/embed.html">
              <i class="fas fa-expand-arrows-alt fa-fw"></i>
            </a>
          </div>
          <div id="breadcrumbs">
            <span id="sidebar-toggle-span">
              <a href="#" id="sidebar-toggle" class="topbar-link" title='Menu (CTRL+ALT+n)'><i class="fas fa-bars fa-fw"></i></a>
            </span>
            <ol class="links" itemscope itemtype="http://schema.org/BreadcrumbList">
              <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><a itemprop="item" href="https://ksu-cs-textbooks.github.io/cc210/index.html"><span itemprop="name">CC 210 Textbook</span></a><meta itemprop="position" content="1"> &gt; </li>
              <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><a itemprop="item" href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/index.html"><span itemprop="name">Exceptions</span></a><meta itemprop="position" content="2"> &gt; </li>
              <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><span itemprop="name">Python Exceptions</span><meta itemprop="position" content="3"></li>
            </ol>
          </div>
        </div>
      </nav>
      <main id="body-inner" class="highlightable chapter narrow" tabindex="-1">
        <div class="flex-block-wrapper">
          <article class="chapter">
            <header class="headline">
            </header>


<div class="article-subheading">Chapter 6.P</div>
<h1 id="python-exceptions">Python Exceptions</h1>

<p>Exceptions in Python</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Python Exceptions</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="common-exceptions">Common Exceptions</h1>

<p>Before we learn about how to detect and handle exceptions in Python, let&rsquo;s review some of the common exceptions and errors we may see in our programs. Each of the headers below is the name of an exception in Python, which is represented by a particular class in the Python programming language.</p>
<h2 id="exception">Exception</h2>
<p>Every exception that can be handled in Python is a subtype of the Exception class. So, when we aren&rsquo;t sure which type of exception to expect, we can always use the Exception class to make sure we catch all of them.</p>
<h2 id="arithmeticerror">ArithmeticError</h2>
<p>An ArithmeticError can occur whenever our program attempts to perform a calculation that would result in an error. This is the base class for various other errors, such as OverflowError and ZeroDivisionError</p>
<h2 id="overflowerror">OverflowError</h2>
<p>An OverflowError occurs when the result of a calculation cannot be represented correctly. Typically this exception is very rare, but can happen when working with older code or libraries.</p>
<h2 id="zerodivisionerror">ZeroDivisionError</h2>
<p>A ZeroDivisionError is thrown whenever the program is asked to either divide by $0$ or perform the modulo operation with $0$ as the second input. Here&rsquo;s an example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span> <span style="color:#f92672">/</span> <span style="color:#ae81ff">0</span> <span style="color:#75715e"># throws ZeroDivisionError</span>
</span></span><span style="display:flex;"><span>y <span style="color:#f92672">=</span> <span style="color:#ae81ff">3</span> <span style="color:#f92672">%</span> <span style="color:#ae81ff">0</span> <span style="color:#75715e"># throws ZeroDivisionError</span></span></span></code></pre></div><h2 id="indexerror">IndexError</h2>
<p>An IndexError happens when we try to access an array index that does not exist. Here&rsquo;s a great example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>array <span style="color:#f92672">=</span> [<span style="color:#ae81ff">1</span>, <span style="color:#ae81ff">2</span>, <span style="color:#ae81ff">3</span>, <span style="color:#ae81ff">4</span>, <span style="color:#ae81ff">5</span>]
</span></span><span style="display:flex;"><span>array[<span style="color:#ae81ff">5</span>] <span style="color:#f92672">=</span> <span style="color:#ae81ff">10</span> <span style="color:#75715e"># throws IndexError</span></span></span></code></pre></div><p>In this example, we are trying to access the 6th element in the array, which is at array index 5. However, since the size of the array is only 5, we&rsquo;ll get an IndexError when we try to execute this code since there is no 6th element.</p>
<h2 id="nameerror">NameError</h2>
<p>In Python, a NameError occurs when we try to use the name of a variable, class, or other item which Python can&rsquo;t find. For example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span> <span style="color:#f92672">+</span> y <span style="color:#75715e"># throws NameError</span></span></span></code></pre></div><p>In this code, we are trying to use the variable <code>y</code> without first giving it a value. When we execute this code, it will throw a NameError.</p>
<h2 id="filenotfounderror">FileNotFoundError</h2>
<p>This exception occurs when the program is trying to open a file that does not exist. This is one of the more common errors that programmers must deal with when using files for input, and it is relatively simple to correct. In most cases, we can simply ask the user to provide another file. Here&rsquo;s an example of some code that may cause this exception:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>filename <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;&#34;</span>
</span></span><span style="display:flex;"><span>reader <span style="color:#f92672">=</span> open(filename) <span style="color:#75715e"># throws FileNotFoundError</span></span></span></code></pre></div><p>In this case, we are providing a blank filename, which causes the program to throw a FileNotFoundError.</p>
<h2 id="typeerror">TypeError</h2>
<p>A TypeError occurs when we try to use a variable in a way that is not allowed based on the type of the variable. We&rsquo;ve probably already seen this exception many times when working with string outputs. Here&rsquo;s an example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span>
</span></span><span style="display:flex;"><span>print(<span style="color:#e6db74">&#34;Number: &#34;</span> <span style="color:#f92672">+</span> x) <span style="color:#75715e"># throws TypeError</span></span></span></code></pre></div><p>In this code, we are using the plus <code>+</code> operator to concatenate two strings together. However, the second variable, <code>x</code>, is an integer, so it is not the correct type for this operation. Therefore, the code will produce a TypeError when executed.</p>
<h2 id="valueerror">ValueError</h2>
<p>A ValueError typically occurs when an input to a method is an acceptable type but has an incorrect value. Here are a couple of examples:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> int(<span style="color:#e6db74">&#34;12.3&#34;</span>) <span style="color:#75715e"># throws ValueError</span>
</span></span><span style="display:flex;"><span>y <span style="color:#f92672">=</span> float(<span style="color:#e6db74">&#34;abc&#34;</span>) <span style="color:#75715e"># throws ValueError</span></span></span></code></pre></div><p>In both of these examples, the <code>int</code> and <code>float</code> methods are provided with the correct type of input, a string. However, neither of those strings can be converted to the corresponding type, so a ValueError is thrown.</p>
<h2 id="assertionerror">AssertionError</h2>
<p><a href="https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement" target="_blank">Python Assertions</a>
</p>
<p>An AssertionError happens when our code reaches an <em>assertion</em> that fails. An assertion is a check added by the programmer to verify that a particular situation doesn&rsquo;t occur in the code, such as a variable being negative or an array being too large. Python supports the use of a special keyword <code>assert</code> that can be used to add these assertions to our code. By default, the Python interpreter enforces all <code>assert</code> statements, but they can easily be disabled by adding <code>-O</code> as an argument to the <code>python3</code> command when running a program. This is a helpful step when debugging a new application. We&rsquo;ll learn more about assertions and how they can be used effectively in a later chapter.</p>
<p>For now, here&rsquo;s a quick example of an assertion that would produce an AssertionError:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span>
</span></span><span style="display:flex;"><span>y <span style="color:#f92672">=</span> <span style="color:#ae81ff">3</span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">assert</span> x <span style="color:#f92672">+</span> y <span style="color:#f92672">&lt;</span> <span style="color:#ae81ff">7</span> <span style="color:#75715e"># throws AssertionError if enabled</span></span></span></code></pre></div><h2 id="errors">Errors</h2>
<p>Beyond exceptions, there are a few unrecoverable errors that may occur in our Python code. Recall that errors are special types of exceptions that should not be handled by our programs, and should instead be allowed to cause our programs to crash. Some examples are:</p>
<ul>
<li>SyntaxError - occurs when the Python interpreter finds code with invalid syntax</li>
<li>IndentationError - occurs when the Python interpreter  finds improperly indented code</li>
<li>SystemError - occurs when the Python interpreter encounters an internal error</li>
</ul>
<p>Since Python is an interpreted language, these errors will occur when code is running, sometimes even after most of the program is executed. In general, we should not try to catch or correct these errors in our code. Instead, we should allow our program to crash, knowing that we&rsquo;ll have to fix the underlying source code to solve the problem.</p>
<h3 id="references">References:</h3>
<ul>
<li><a href="https://docs.python.org/3/library/exceptions.html" target="_blank">Built-in Exceptions</a>
</li>
<li><a href="https://docs.python.org/3/tutorial/errors.html" target="_blank">Tutorial: Errors and Exceptions</a>
</li>
</ul>

            <footer class="footline">

            </footer>
          </article>

    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="exceptions-vs-errors">Exceptions vs. Errors</h1>

<p>Since Python is an interpreted language, it can be hard to tell the difference between <em>exceptions</em> and <em>errors</em>. So, let&rsquo;s take a minute to review those two terms and what they mean.</p>
<h2 id="exceptions">Exceptions</h2>
<p>An <em>exception</em> is any issue encountered while executing a program that can be resolved within the program itself. Typically most exceptions come from incorrect user input, but they can be caused by other issues as well. However, just because an exception can be resolved by the program does not automatically mean that the program does, or must, include a handler for that exception. It just means that it could handle the exception, if the developer included the appropriate handler and code.</p>
<h2 id="errors">Errors</h2>
<p>As discussed before, <em>errors</em> are a special type of exception that cannot be easily handled by the program. These are usually due to issues in the underlying operating system or problems in the code itself. The Python interpreter may return errors such as SyntaxError or IndentationError relating to issues with the code, but it also may return errors such as SystemError or OSError if it encounters a problem that it cannot easily resolve.</p>

            <footer class="footline">

            </footer>
          </article>

    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="try-except">Try-Except</h1>

<p><a href="https://www.youtube.com/watch?v=VRg7hkkY4iI">YouTube Video</a></p>
<!-- TODO Update Video? -->
<p><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/03-try-except/video/">Video Materials</a>
</p>
<p>Programs written in Python can have many exceptions occur on a regular basis. Thankfully, as we learned earlier, it is possible to detect and handle these exceptions in our code directly, in order to prevent our program crashing and causing the user more stress. Let&rsquo;s see how we can perform this step in Python.</p>
<p>Consider the following program, if provided a command-line argument, it treats that string as a file-name and opens it for reading.  If there is no command-lie argument, it defaults to keyboard entry.  It then attempts to get an input and convert that to an integer.</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">Try</span>:
</span></span><span style="display:flex;"><span>    
</span></span><span style="display:flex;"><span>    <span style="color:#a6e22e">@classmethod</span>
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">def</span> <span style="color:#a6e22e">main</span>(cls, args):
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>            reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>            reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>        x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>        print(x)
</span></span><span style="display:flex;"><span>           
</span></span><span style="display:flex;"><span>        
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">if</span> __name__ <span style="color:#f92672">==</span> <span style="color:#e6db74">&#34;__main__&#34;</span>:
</span></span><span style="display:flex;"><span>    Try<span style="color:#f92672">.</span>main(sys<span style="color:#f92672">.</span>argv)</span></span></code></pre></div><h2 id="try-except">Try-Except</h2>
<p>In Python, we use a <strong>Try-Except</strong> construct to detect and handle exceptions in our code. Let&rsquo;s look at a quick example, and then we can discuss how it works.</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>  print(x)
</span></span><span style="display:flex;"><span>    
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">Exception</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error!&#34;</span>)</span></span></code></pre></div><p>First, we use the <code>try</code> keyword, followed by a colon <code>:</code> to begin a block of code. Below that, we indent any lines to be included in the <code>try</code> block. If any exceptions occur in the code indented below a <code>try</code> keyword, we can add <code>except</code> statements to handle that exception.</p>
<p>Directly following the <code>try</code> block, we must include at least one <code>except</code> statement. The <code>except</code> keyword is followed by the name of an exception that we&rsquo;d like to catch. Optionally we can add the <code>as</code> keyword and the name of a variable to represent that exception. Finally, we include a colon <code>:</code> and indent a block of code below to act as the exception handler.</p>
<p>In this example, we are just catching the generic <code>Exception</code> type, which will match any catchable exception. We&rsquo;ll see how we can detect specific exceptions in a later example. We can use the variable for the exception, in this case <code>e</code>, to access additional details about the exception we&rsquo;ve detected.</p>
<p style="padding:10"><b>Note:</b> nearly every other language uses the syntax "try catch" instead of "try except". </p>
<h2 id="which-exceptions-to-catch">Which Exceptions to Catch?</h2>
<p>When writing code, it can sometimes be very difficult to even know which exceptions to expect from a particular piece of code. Thankfully, the <a href="https://docs.python.org/3/library/exceptions.html" target="_blank">Python Documentation</a>
 includes quite a bit of information about the possible exceptions that could occur in a program.</p>
<p>Let&rsquo;s return to our earlier example. Here is the code contained in the <code>try</code> block:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>  reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])  
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>  reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>print(x)</span></span></code></pre></div><p>While this may look like a very simple few lines of code, there are actually several exceptions that could be produced here:</p>
<ul>
<li>FileNotFoundError - if the file in <code>args[1]</code> is not valid</li>
<li>NameError - if we forget to include <code>import sys</code> at the top of the file</li>
<li>ValueError - if the input cannot be converted to an integer</li>
<li>IndexError - <code>args[1]</code> could produce this exception, but we&rsquo;ve already checked that the length is greater than 1, so it won&rsquo;t happen in practice.</li>
</ul>
<p>When writing truly bulletproof code, it is a good idea to attempt to catch and handle all of these exceptions if possible. You can always refer to the official Python documentation for a list of exceptions that could occur. Unfortunately, Python does not do a great job of documenting which exceptions could be thrown by specific methods compared to Java. Later on in this chapter we&rsquo;ll discuss some best practices when it comes to detecting and handling exceptions in code.</p>
<h2 id="handling-multiple-exceptions">Handling Multiple Exceptions</h2>
<p>Of course, we can add multiple <code>except</code> statements after any <code>try</code> block to catch different types of exceptions.</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># If an argument is present, we are reading from a file</span>
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># specified in args[1]</span>
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># If no argument, read from stdin  </span>
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>  print(x)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">FileNotFoundError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: File Not Found!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: Input Does Not Match Expected Format!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">OSError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: OS Exception!&#34;</span>)</span></span></code></pre></div><p>In the example code above, we see three different <code>except</code> statements, each of which will handle a different type of exception. When an exception occurs in the code contained in a <code>try</code> block, the Python interpreter will create the exception, and then it will search for the first handler that matches. So, it will begin with the first <code>except</code> statement, and see if the exception created matches the type of the exception in parenthesis. If so, it will execute the code inside of that <code>except</code> block. If not, it will continue to the next <code>except</code> statement. If none of the <code>except</code> statements match the exception, then it will be <em>thrown</em> and cause the program to stop executing.</p>
<h2 id="exception-hierarchy">Exception Hierarchy</h2>
<p>The exceptions in Python form a hierarchical structure, meaning that an exception may match multiple types. For example, all exceptions that programs can catch are based on the generic Exception type. So, FileNotFoundError and IndexError would both match the Exception type.</p>
<p>In addition, many exceptions are descended from the OSError type. For example, FileNotFoundError is based on OSError, which itself is based on the Exception type. So, a FileNotFoundError would match any of those three types of exceptions. It can make things a bit tricky!</p>
<p>So, how can we know what types of exceptions we are dealing with, and what the hierarchy is? Thankfully, the <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy" target="_blank">Python Documentation</a>
 contains information about most possible exceptions, including the entire hierarchy of those exceptions.</p>
<p>For example, here is a screenshot from the <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy" target="_blank">Python Documentation</a>
 page showing the hierarchy of OSError:</p>
<p>
<a href="#image-89196fe09fa985b2b1e62cba82bf240f" class="lightbox-link">
<img src="https://ksu-cs-textbooks.github.io/cc210/images/10-except/8.7.p.3.filenotfound.png" alt="OSError Hierarchy" style="height: auto; width: auto;" loading="lazy">
</a>
<a href="javascript:history.back();" class="lightbox" id="image-89196fe09fa985b2b1e62cba82bf240f">
<img src="https://ksu-cs-textbooks.github.io/cc210/images/10-except/8.7.p.3.filenotfound.png" alt="OSError Hierarchy" class="lightbox-image" loading="lazy">
</a></p>
<p>Because of this, we must be careful about how we order the catch statements. In general, we want to place the more specific exceptions first (the ones further down the hierarchy), and the more generic exceptions later.</p>
<p>Let&rsquo;s look at an example of poor ordering of exception handlers:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># If an argument is present, we are reading from a file</span>
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># specified in args[1]</span>
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># If no argument, read from stdin  </span>
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>  print(x)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">OSError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: OS Exception!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">FileNotFoundError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: File Not Found!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: Input Does Not Match Expected Format!&#34;</span>)</span></span></code></pre></div><p>In the code above, we are catching the OSError first. So, if the code produces a FileNotFoundError, it will be caught and handled by the first <code>except</code> statement, since FileNotFoundError is also an OSError. Therefore, we wouldn&rsquo;t want to order our <code>except</code> statements in this way.</p>
<h2 id="try-it">Try It!</h2>
<p>Let&rsquo;s see if we can write a very simple program to catch and handle a few common exceptions. Here&rsquo;s some starter code for <code>main</code>&rsquo;s:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>  reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>  reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>y <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>z <span style="color:#f92672">=</span> x <span style="color:#f92672">/</span> y
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>print(z)</span></span></code></pre></div><p>For this example, place this starter code in <code>Try.py</code>, open to the left, and modify it to catch and handle the following exceptions by printing the given error messages:</p>
<ul>
<li>FileNotFoundError - print &ldquo;Error: File Not Found!&rdquo;</li>
<li>ValueError - print &ldquo;Error: Input Does Not Match Expected Format!&rdquo;</li>
<li>ZeroDivisionError - print &ldquo;Error: Divide by Zero!&rdquo;</li>
</ul>
<p>Any other exceptions can be ignored.</p>

  
    
    
  
  
<div class="box notices cstyle noiframe">
  <div class="box-label"><i class="fa-fw fas fa-times-circle"></i> Web Only</div>
  <div class="box-content">

<p>This content is presented in the course directly through Codio. Any references to interactive portions are only relevant for that interface. This content is included here as reference only.</p>
</div>
</div>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Try-Except</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="python-try-except">Python Try-Except</h1>


<a href="https://www.youtube.com/watch?v=E74G8iTdgBE">YouTube Video</a>

<h4 id="resources">Resources</h4>
<ul>
<li><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/03-try-except/video/slides/" target="_blank">Slides</a></li>
</ul>
<h4 id="video-script">Video Script</h4>
<p>Let&rsquo;s take a closer look at how we can use a <strong>Try-Except</strong> statement in Python to detect and handle exceptions that are caused by our program. Specifically want to take a program that looks like this, and update it to look more like this, with code to catch and handle exceptions that are thrown by the program.</p>
<p>To do this, we can start with a simple program. This program is very similar to the skeleton code we&rsquo;ve been using throughout the textbook. In this program, we can either accept input from a file if one is provided as a command-line argument. If not, we&rsquo;ll accept input via the terminal. The program will then read a single integer from input, and print that integer to the terminal. Even though this is a very simple program, as we&rsquo;ll soon see, there are lots of ways it can cause an exception.</p>
<p>First, let&rsquo;s look at the general case and just try to catch all possible exceptions in the program. To do that, we must first surround all of the code with a <strong>Try</strong> block. We can omit the import statement at the top of the program, since it cannot possibly cause an exception. Of course, when we add a <strong>Try</strong> block, we&rsquo;ll need to make sure we indent everything inside of it as well, just to make our code more readable.</p>
<p>Once we have our <strong>Try</strong> block in place, we must add at least one <strong>Except</strong> block afterwards. Every <strong>Try</strong> block must include at least one <strong>Except</strong> block in order to be valid. So, we&rsquo;ll add a <strong>Except</strong> block to the bottom of our code.</p>
<p>Inside of the <strong>Except</strong> block, we&rsquo;ve chosen to catch the generic Exception, which covers all possible exceptions. We&rsquo;re also using the <code>as</code> keyword to assign the caught exception to a variable, in this case <code>e</code>.</p>
<p>Finally, inside of the <strong>Except</strong> block, we can add code to handle the exception. In this case, we&rsquo;ll simply print an error message to the screen, alerting the user that an exception has occurred. Later in this chapter, we&rsquo;ll see other ways to handle the exceptions beyond just printing a message, but for now it makes our programs easy to follow.</p>
<p>There we go! We&rsquo;ve successfully modified our program to catch and handle any possible exception. However, this may not be very useful, since our program is unable to tell us exactly what type of exception has occurred. Likewise, the only message the user gets is &ldquo;Error&rdquo; without any additional context. Can we modify our program to catch and handle more specific exceptions?</p>
<p>We sure can! Let&rsquo;s look at some of the possible exceptions that could occur in this code. First, we notice here that we are opening a file. So, there is always a possibility that the file provided as input doesn&rsquo;t exist. In that case, the program would throw a FileNotFoundError. So, we can modify our existing <strong>Except</strong> statement to catch a FileNotFoundError instead. When we do that, we may also want to change the error message printed by the program to be a bit more specific.</p>
<p>Next, we can consider other possible sources of an exception in our program. Since we are converting the input to an integer, it could throw a ValueError if we read anything other than an integer. So, we&rsquo;ll need to add one more <strong>Except</strong> statement to handle that exception as well.</p>
<p>Finally, we might notice that the program is reading input from a file. Whenever we do that, there is a possibility that the program could throw an OSError, especially if the file we are reading from becomes unavailable or is damaged. So, to handle that exception, we can add a second <strong>Except</strong> statement below the others. This one will catch an OSError.</p>
<p>At this point, let&rsquo;s take a step back and consider an important question: does the order of these catch statements matter? For example, what if I reorder them, putting the OSError first, like this? Would that work?</p>
<p>Unfortunately, this would not work the way we want it to. This is because exceptions in Python are hierarchical, meaning that some exceptions are more specific versions of others. In this case, the FileNotFoundError is a more specific version of an OSError. We can find this in the Python documentation, shown here. The link to this documentation can be found in the textbook.</p>
<p>So, whenever a FileNotFoundError is thrown, it will be handled by the first <strong>Except</strong> statement in this example instead of the second one, which is where we want it to be handled. Therefore, it is recommended to always place the <strong>Except</strong> statements for the most specific exceptions first, and then the more general ones later. So, we&rsquo;ll need to go back to the way these were ordered previously.</p>
<p>There we go! We&rsquo;ve taken a simple program, and added a <strong>Try-Except</strong> statement to handle many different exceptions that could occur while running this code. It is always a good idea to catch and handle exceptions whenever possible in your code so your programs are much more user friendly and don&rsquo;t crash when they run into problems.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Python Try-Except</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id=""></h1>

<br>
<section>
	<img class="stretch plain" src="https://ksu-cs-textbooks.github.io/cc210/images/10-except/8.4.handle.png">
</section><br>
<section>
	<img class="stretch plain" src="https://ksu-cs-textbooks.github.io/cc210/images/10-except/8.4.try.png">
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
# If an argument is present, we are reading from a file
# specified in sys.argv[1]
if len(sys.argv) > 1:
  reader = open(sys.argv[1])<br>
# If no argument, read from stdin
else:
  reader = sys.stdin<br>
x = int(reader.readline())
print(x)
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
<mark>try:</mark>
# If an argument is present, we are reading from a file
# specified in sys.argv[1]
if len(sys.argv) > 1:
  reader = open(sys.argv[1])<br>
# If no argument, read from stdin
else:
  reader = sys.stdin<br>
x = int(reader.readline())
print(x)
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
<mark># If an argument is present, we are reading from a file
# specified in sys.argv[1]
if len(sys.argv) > 1:
  reader = open(sys.argv[1])<br>
# If no argument, read from stdin
else:
  reader = sys.stdin<br>
x = int(reader.readline())
print(x)</mark>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  <mark># If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)</mark>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)
</code></pre>
</section><br><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
<mark>except Exception as e:</mark><br>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except <mark>Exception</mark> as e:<br>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except Exception <mark>as</mark> e:<br>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except Exception as e:<br>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except Exception as e:
  <mark>print("Error!")</mark>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except Exception as e:
  print("Error!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = <mark>open(sys.argv[1])</mark><br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except Exception as e:
  print("Error!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except <mark>Exception</mark> as e:
  print("Error!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except <mark>FileNotFoundError</mark> as e:
  print("Error!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print(<mark>"Error!"</mark>)
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print(<mark>"Error: File Not Found!"</mark>)
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = <mark>int(reader.readline())</mark>
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
<mark>except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")</mark>
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(<mark>reader.readline()</mark>)
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")
<mark>except OSError as e:
  print("Error: OS Exception!")
</code></pre>
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")
except OSError as e:
  print("Error: OS Exception!")
</code></pre>
</section><br><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
<mark>except OSError as e:
  print("Error: OS Exception!")
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")</mark>
</code></pre>
</section><br><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
<mark style="background-color: red">except OSError as e:
  print("Error: OS Exception!")
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")</mark>
</code></pre>
</section><br><br>
<section>
	<h2>Exception Hierarchy</h2>
	<img class="stretch plain" src="https://ksu-cs-textbooks.github.io/cc210/images/10-except/8.7.p.3.filenotfound.png">
</section><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
<mark style="background-color: red">except OSError as e:
  print("Error: OS Exception!")
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")</mark>
</code></pre>
</section><br><br><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
<mark>except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")
except OSError as e:
  print("Error: OS Exception!")</mark>
</code></pre>
</section><br><br>
<section>
	<pre class="stretch" style="font-size: .49em"><code class="python"># Load required modules
import sys<br>
try:
  # If an argument is present, we are reading from a file
  # specified in sys.argv[1]
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])<br>
  # If no argument, read from stdin
  else:
    reader = sys.stdin<br>
  x = int(reader.readline())
  print(x)<br>
except FileNotFoundError as e:
  print("Error: File Not Found!")
except ValueError as e:
  print("Error: Input Does Not Match Expected Format!")
except OSError as e:
  print("Error: OS Exception!")
</code></pre>
</section><br>
            <footer class="footline">

            </footer>
          </article>

          </section>
          </section>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="raise">Raise</h1>

<p><a href="https://www.youtube.com/watch?v=WTo7Xdrg0Ec">YouTube Video</a></p>
<p><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/04-raise/video/">Video Materials</a>
</p>
<p>Beyond catching exceptions, there are a few other important concepts to learn related to exceptions. Let&rsquo;s go over a couple of them.</p>
<h2 id="raise">Raise</h2>
<p>We can generate our own exceptions using the <code>raise</code> keyword. This allows us to create new exceptions whenever needed. Let&rsquo;s look at an example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">Raise</span>:
</span></span><span style="display:flex;"><span>    
</span></span><span style="display:flex;"><span>    <span style="color:#a6e22e">@classmethod</span>
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">def</span> <span style="color:#a6e22e">main</span>(cls, args):       
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>          reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>          reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>        x <span style="color:#f92672">=</span> float(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>        y <span style="color:#f92672">=</span> float(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">if</span> y <span style="color:#f92672">==</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>          <span style="color:#66d9ef">raise</span> <span style="color:#a6e22e">ValueError</span>(<span style="color:#e6db74">&#34;Cannot divide by zero&#34;</span>)
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>          z <span style="color:#f92672">=</span> x <span style="color:#f92672">/</span> y
</span></span><span style="display:flex;"><span>          print(z)</span></span></code></pre></div><p>In this code, we are asking the user to input two floating point numbers. Then, we will output the first number divided by the second. However, we want to avoid the situation where the second number, the divisor, is $0$. Instead of causing a DivideByZeroError, we can use an <strong>If-Then</strong> statement and the <code>raise</code> keyword to send a ValueError instead.</p>
<p>Following the <code>raise</code> keyword, we must create a new Exception. In this case, we are creating a new ValueError, but any of the exception types we&rsquo;ve learned about so far will work the same way. Inside of the parentheses, we can provide a helpful error message to go along with this exception.</p>
<h2 id="try-it">Try It!</h2>
<p>Let&rsquo;s see if we can use these keywords in another example. We&rsquo;ll start with this code in <code>main()</code>:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">if</span> len(args) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>  reader <span style="color:#f92672">=</span> open(args[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>  reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin</span></span></code></pre></div><p>Place this code in <code>Raise.py</code> and modify it to do the following:</p>
<ol>
<li>If the user provides an invalid file name in the arguments array, it should throw a FileNotFoundError.</li>
<li>It should read a single string of input from the user. To make this simple, don&rsquo;t forget to use the <code>strip()</code> method to remove any extra whitespace and trailing newline characters!</li>
<li>If the string does not begin with a capital letter, it should throw a new ValueError that contains the error message &ldquo;Proper Capitalization Required!&rdquo;</li>
<li>Of course, if the string is empty, it should throw an IndexError with the message &ldquo;String is Empty!&rdquo; when it tries to access the first character of the string.</li>
<li>Otherwise, it should print the string to the terminal.</li>
</ol>

  
    
    
  
  
<div class="box notices cstyle noiframe">
  <div class="box-label"><i class="fa-fw fas fa-times-circle"></i> Web Only</div>
  <div class="box-content">

<p>This content is presented in the course directly through Codio. Any references to interactive portions are only relevant for that interface. This content is included here as reference only.</p>
</div>
</div>
<h3 id="passing-back-text">Passing Back Text</h3>
<p>The construct <code>raise &lt;exception&gt;(&lt;string&gt;)</code> returns an <code>&lt;class:ValueError&gt;</code> object.  Like all objects it has a <code>__str__</code> method that is called when <code>print</code>ed or used with <code>str()</code>.  The value returned is by <code>str()</code> is <code>&lt;string&gt;</code>.</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">raise</span> <span style="color:#a6e22e">ValueError</span>(<span style="color:#e6db74">&#34;demo&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>   print(type(e)) <span style="color:#75715e"># &lt;class &#39;ValueError&#39;&gt;</span>
</span></span><span style="display:flex;"><span>   print(e)       <span style="color:#75715e"># &#34;demo&#34;</span></span></span></code></pre></div><p>This behavior is convenient when a single type of exception can be triggered by different causes.  Each <code>raise ..</code>  can have a different explanatory string or error message.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Raise</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="python-raise">Python Raise</h1>


<a href="https://www.youtube.com/watch?v=WTo7Xdrg0Ec">YouTube Video</a>

<h4 id="resources">Resources</h4>
<ul>
<li><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/04-raise/video/slides/" target="_blank">Slides</a></li>
</ul>
<h4 id="video-script">Video Script</h4>
<p>We can also create our own custom exceptions in Python. This can be really helpful in some of our programs.</p>
<p>Consider the following program. It reads two floating-point numbers as input, then tries to divide the first number by the second number. If we recall our basic math training, we realize that we could cause an error if the second input is exactly 0, which would make our program divide by 0. While we could just let the program handle that exception, we can also throw our own exception with more information for the user.</p>
<p>To do that, we can simply replace this print statement with a new exception. I chose to use the ValueError here, since it is the one that best represents the type of error that is happening in this code. We can use any existing exception here, including the generic Exception type.</p>
<p>There we go! Now we have a program that throws its own custom exception. Now our users will know exactly what the cause of the problem was, and we can customize the error message as needed to provide even more information to our users.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Python Raise</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id=""></h1>

<br>
<section>
  <h2>Custom Exceptions</h2>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .70em"><code class="python">import sys
<br>
if len(sys.argv) > 1:
  reader = open(sys.argv[1])
else:
  reader = sys.stdin
<br>
x = float(reader.readline())
y = float(reader.readline())
<br>
if y == 0:
  print("Error")
else:
  z = x / y
  print(z)
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .70em"><code class="python">import sys
<br>
if len(sys.argv) > 1:
  reader = open(sys.argv[1])
else:
  reader = sys.stdin
<br>
x = float(reader.readline())
y = float(reader.readline())
<br>
if y == 0:
  <mark>print("Error")</mark>
else:
  z = x / y
  print(z)
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .70em"><code class="python">import sys
<br>
if len(sys.argv) > 1:
  reader = open(sys.argv[1])
else:
  reader = sys.stdin
<br>
x = float(reader.readline())
y = float(reader.readline())
<br>
if y == 0:
  <mark>raise ValueError("Cannot divide by zero")</mark>
else:
  z = x / y
  print(z)
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .70em"><code class="python">import sys
<br>
if len(sys.argv) > 1:
  reader = open(sys.argv[1])
else:
  reader = sys.stdin
<br>
x = float(reader.readline())
y = float(reader.readline())
<br>
if y == 0:
  raise ValueError("Cannot divide by zero")
else:
  z = x / y
  print(z)
</code></pre>
</section>
<br>
            <footer class="footline">

            </footer>
          </article>

          </section>
          </section>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="else--finally">Else &amp; Finally</h1>

<p><a href="https://www.youtube.com/watch?v=L7hep4SmBpo">YouTube Video</a></p>
<p><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/05-else-finally/video/">Video Materials</a>
</p>
<p>When dealing with exceptions in our code, sometimes we have an operation that must be executed, even if the earlier code throws an exception. In that case, we can use the <code>finally</code> keyword to make sure that the correct code is executed. In addition, we may have an operation that should only happen if there are no exceptions in the previous code. For that, we can use the <code>else</code> keyword.</p>
<h2 id="finally">Finally</h2>
<p>To understand how the <code>finally</code> keyword works, let&rsquo;s take a look at an example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&lt;</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">raise</span> <span style="color:#a6e22e">ValueError</span>(<span style="color:#e6db74">&#34;Input must be greater than 0!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Value Error: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e))
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">finally</span>:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Finally Block&#34;</span>)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>print(<span style="color:#e6db74">&#34;After Try&#34;</span>)</span></span></code></pre></div><p>This program will read an integer from the terminal. If the integer is greater than or equal to 0, it will do nothing except print the &ldquo;Finally Block&rdquo; and &ldquo;After Try&rdquo; messages. However, if the input is less than 0, it will throw a ValueError. Finally, if the input is not a number, then a ValueError will also be thrown and handled. In each of those cases, it will also print the &ldquo;Finally Block&rdquo; message.</p>
<p>Let&rsquo;s run this program a few times and see how it works. First, we&rsquo;ll provide the input &ldquo;5&rdquo;:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span><span style="color:#e6db74">$</span> python<span style="color:#ae81ff">3</span> <span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>Finally.py
</span></span><span style="display:flex;"><span><span style="color:#ae81ff">5</span>
</span></span><span style="display:flex;"><span>Finally Block
</span></span><span style="display:flex;"><span>After Try</span></span></code></pre></div><p>Here, we can see that the code in the <code>finally</code> block always runs when the program is finished executing the statements in the <code>try</code> block.</p>
<p>Let&rsquo;s run it again, this time with &ldquo;-5&rdquo; as the input:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span><span style="color:#e6db74">$</span> python<span style="color:#ae81ff">3</span> <span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>Finally.py
</span></span><span style="display:flex;"><span><span style="color:#f92672">-</span><span style="color:#ae81ff">5</span>
</span></span><span style="display:flex;"><span>Value Error: Input must be greater than <span style="color:#ae81ff">0</span><span style="color:#f92672">!</span>
</span></span><span style="display:flex;"><span>Finally Block
</span></span><span style="display:flex;"><span>After Try</span></span></code></pre></div><p>Here, we can see that it prints the error message caused by the ValueError, then proceeds to the <code>finally</code> block. So, even if an exception is thrown while inside of the <code>try</code> block, the code in the <code>finally</code> block is <strong>always</strong> executed once the <code>try</code> block and any exception handlers are finished.</p>
<p>Here&rsquo;s one more example, this time with &ldquo;abc&rdquo; as the input:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span><span style="color:#e6db74">$</span> python<span style="color:#ae81ff">3</span> <span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>Finally.py
</span></span><span style="display:flex;"><span>abc
</span></span><span style="display:flex;"><span>Value Error: invalid literal for int<span style="color:#f92672">()</span> with base <span style="color:#ae81ff">10</span>: &#39;abc\n&#39;
</span></span><span style="display:flex;"><span>Finally Block
</span></span><span style="display:flex;"><span>After Try</span></span></code></pre></div><p>Once again, we see that the code first handles the ValueError, and then it will execute the code in the <code>finally</code> block.</p>
<p>In a later chapter, we&rsquo;ll learn more about how to use the <code>finally</code> block to perform important tasks such as closing open files and making sure we don&rsquo;t leave the system in an unstable state when we handle an exception.</p>
<h2 id="else">Else</h2>
<p>Python also allows the <code>else</code> keyword to be used with a <strong>Try-Except</strong> statement. It works similarly to the way Python handles the <code>else</code> keyword with loops. Let&rsquo;s look at an example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&lt;</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">raise</span> <span style="color:#a6e22e">ValueError</span>(<span style="color:#e6db74">&#34;Input must be greater than 0!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Value Error: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e))
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;No Errors!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">finally</span>:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Finally Block&#34;</span>)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>print(<span style="color:#e6db74">&#34;After Try&#34;</span>)</span></span></code></pre></div><p>The code above is the same example used to demonstrate the <code>finally</code> keyword, but now there is an <code>else</code> block added. The code in the <code>else</code> block will be executed only if the entire code in the <code>try</code> block is able to execute without any errors or exceptions being raised.</p>
<p>So, if we run this program with the input <code>5</code>, we&rsquo;ll get the following:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span><span style="color:#e6db74">$</span> python<span style="color:#ae81ff">3</span> <span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>Finally.py
</span></span><span style="display:flex;"><span><span style="color:#ae81ff">5</span>
</span></span><span style="display:flex;"><span>No Errors<span style="color:#f92672">!</span>
</span></span><span style="display:flex;"><span>Finally Block
</span></span><span style="display:flex;"><span>After Try</span></span></code></pre></div><p>Since this program does not encounter any exceptions, the <code>else</code> block is executed immediately after the <code>try</code> block, but before the <code>finally</code> block. However, if we provide an invalid input, such as <code>-5</code>, the output will look like this instead:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span><span style="color:#e6db74">$</span> python<span style="color:#ae81ff">3</span> <span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>Finally.py
</span></span><span style="display:flex;"><span><span style="color:#f92672">-</span><span style="color:#ae81ff">5</span>
</span></span><span style="display:flex;"><span>Value Error: Input must be greater than <span style="color:#ae81ff">0</span><span style="color:#f92672">!</span>
</span></span><span style="display:flex;"><span>Finally Block
</span></span><span style="display:flex;"><span>After Try</span></span></code></pre></div><p>Since this program encountered an exception, the code in the <code>else</code> block is not executed. However, the code in the <code>finally</code> block is still executed, since it will happen regardless of the outcome of the <code>try</code> block.</p>
<p>Finally, it is possible to include an <code>else</code> block without a <code>finally</code> block if desired. The only rule is that the <code>else</code> block must come before the <code>finally</code> block, and both of them should be after any <code>except</code> blocks to handle exceptions.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Else &amp; Finally</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="python-else--finally">Python Else &amp; Finally</h1>


<a href="https://www.youtube.com/watch?v=L7hep4SmBpo">YouTube Video</a>

<h4 id="resources">Resources</h4>
<ul>
<li><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/05-else-finally/video/slides/" target="_blank">Slides</a></li>
</ul>
<h4 id="video-script">Video Script</h4>
<p>There are some situations where we might need to be sure a particular piece of code always executes , even if our program reaches an exception. For example, if we are reading or writing to a file, we should always close that file when we are done, even if we encounter an error. To do that, we can add a <strong>Finally</strong> block to our programs in Python.</p>
<p>Consider this sample program. It includes a <strong>Try-Except</strong> statement already. To add a <strong>Finally</strong> block, we simply add i t at the end of the <strong>Except</strong> statements, just like any other. Inside of that <strong>Finally</strong> block, we can include any code needed. In this case, we&rsquo;re just going to print a message showing that we&rsquo;ve executed the code in that block. You&rsquo;ll also notice that we&rsquo;ve included another print statement outside of the <strong>Try-Except</strong> block as well, just so we know that we&rsquo;ve completely exited that block of code.</p>
<p>To really understand how a <strong>Finally</strong> block works, let&rsquo;s step through this program with several different values provided as input, and see what happens. First, we can provide the input of &ldquo;5&rdquo; to the program. In this case, it is able to successfully read the input and convert it to an integer. Then, it will check to see if the input is less than 0. Since it isn&rsquo;t, we&rsquo;ll move forward, and eventually reach the end of the <strong>Try-Except</strong> block. So, it will now execute the code in the <strong>Finally</strong> block, and print that output to the screen, and then it will exit the block and print the &ldquo;After Try&rdquo; message as well. This is a pretty simple case, since we didn&rsquo;t reach any exceptions.</p>
<p>Let&rsquo;s try it again, but this time we&rsquo;ll provide the input -5. Once again, it is able to read that input and store it as an integer just fine. However, once it reaches the <strong>If-Then</strong> statement, it realizes that the input is less than 0, so it will enter the block and throw a new ValueError. When that happens, the <strong>Try-Except</strong> block will immediately catch and try to handle the exception. So, we&rsquo;ll jump down a bit to the exception handler for ValueError, which will print the error message contained in the exception. Once we&rsquo;ve handled the exception, the code will then move into the <strong>Finally</strong> block and print that output. So, as we can see, the <strong>Finally</strong> block will be executed regardless of whether the <strong>Try-Except</strong> block encountered an exception or not. At the very end, it will print the output outside of the block before exiting the program.</p>
<p>Here&rsquo;s one more input we can trace. This time, we&rsquo;ll provide some text instead of a number. So, when we try to convert the input to an integer, we&rsquo;ll immediately cause a ValueError. That will move our execution down to the exception handler for ValueError again, so we&rsquo;ll print the error there. Once again, we&rsquo;ll immediately move to the <strong>Finally</strong> block and then the code outside the <strong>Try-Except</strong> block.</p>
<p>So, as we have seen through these examples, the <strong>Finally</strong> block is a very handy addition to a <strong>Try-Except</strong> block that allows us to add additional code that will execute at the end of the block, regardless of whether we&rsquo;ve encountered an exception or not. We&rsquo;ll see this used in many cases to handle closing files or resources used in our <strong>Try-Except</strong> statements, though later in this chapter we&rsquo;ll learn about the <strong>With</strong> statement, which is another way to handle this situation.</p>
<p>There is one other block we can add to our <strong>Try-Except</strong> statements in Python, which is the <strong>Else</strong> block. We can add it to our code just like we did for the <strong>Finally</strong> block. Note that the <strong>Else</strong> block should always be placed after the exception handlers, but before the <strong>Finally</strong> block. In addition, we can also place any code we want inside of the block, but once again we&rsquo;ll use a print statement so we can see when that code is executed.</p>
<p>So, let&rsquo;s go back to our earlier examples and see how this changes things. First, we&rsquo;ll provide 5 as input once again. So, we can successfully read the input, and find that it is greater than 0. After that, since we got all the way through the <strong>Try</strong> block without an exception, we can executed the code in the <strong>Else</strong> block, printing that output to the screen, followed by the <strong>Finally</strong> block and then the code after the <strong>Try-Except</strong> statement.</p>
<p>However, when we provide -5 as input, we&rsquo;ll run into an exception. So, the code will move into the exception handler, then immediately following that it will reach the <strong>Finally</strong> block and exit the <strong>Try-Except</strong> statement. Since there was an exception that was caught by the <strong>Try-Except</strong> statement, the program will skip the <strong>Else</strong> statement entirely.</p>
<p>The <strong>Else</strong> block can be used in a variety of interesting ways. For example, we can accept and read user input in the <strong>Try-Except</strong> block, but only save the data when we reach the <strong>Else</strong> block, since we know that the data collected didn&rsquo;t cause any exceptions. It can be a very powerful feature of the Python programming language.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Python Else &amp; Finally</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id=""></h1>

<br>
<section>
	<pre class="stretch" style="font-size: .7em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<br>
print("After Try")
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .7em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>finally:
  print("Finally Block")</mark>
<br>
print("After Try")
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .7em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  <mark>x = int(reader.readline())</mark>
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  <mark>if x &lt; 0:</mark>
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>finally:</mark>
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  <mark>print("Finally Block")</mark>
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">Finally Block</pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
<mark>print("After Try")</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">Finally Block
After Try</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  <mark>x = int(reader.readline())</mark>
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  <mark>if x &lt; 0:</mark>
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    <mark>raise ValueError("Input must be ...")</mark>
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
<mark>except ValueError as e:</mark>
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  <mark>print("VE: {}".format(e))</mark>
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>finally:</mark>
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  <mark>print("Finally Block")</mark>
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...
Finally Block</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
<mark>print("After Try")</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...
Finally Block
After Try</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  <mark>x = int(reader.readline())</mark>
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
<mark>except ValueError as e:</mark>
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  <mark>print("VE: {}".format(e))</mark>
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: invalid...</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>finally:</mark>
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: invalid...</pre>
  </div>
</section>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  <mark>print("Finally Block")</mark>
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: invalid...
Finally Block</pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
<mark>print("After Try")</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: invalid...
Finally Block
After Try</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">abc</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: invalid...
Finally Block
After Try</pre>
  </div>
</section>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .7em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
</section>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .7em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>else:
  print("No Errors!")</mark>
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .7em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  <mark>x = int(reader.readline())</mark>
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  <mark>if x &lt; 0:</mark>
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>else:</mark>
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  <mark>print("No Errors!")</mark>
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">No Errors!</pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
<mark>finally:</mark>
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">No Errors!</pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  <mark>print("Finally Block")</mark>
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">No Errors!
Finally Block</pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
<mark>print("After Try")</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">No Errors!
Finally Block
After Try</pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  <mark>x = int(reader.readline())</mark>
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  <mark>if x &lt; 0:</mark>
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  <mark>if x &lt; 0:</mark>
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    <mark>raise ValueError("Input must be ...")</mark>
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
<mark>except ValueError as e:</mark>
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em"> </pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  <mark>print("VE: {}".format(e))</mark>
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...</pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
<mark>else:</mark>
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...</pre>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
<mark>finally:</mark>
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  <mark>print("Finally Block")</mark>
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...
Finally Block</pre>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
<mark>print("After Try")</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...
Finally Block
After Try</pre>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .5em"><code class="python">import sys
<br>
reader = sys.stdin
try:
  x = int(reader.readline())
  if x &lt; 0:
    raise ValueError("Input must be ...")
except ValueError as e:
  print("VE: {}".format(e))
else:
  print("No Errors!")
finally:
  print("Finally Block")
<br>
print("After Try")
</code></pre>
  </div>
  <div style="width: 30%">
    <p>Input:</p>
    <pre style="font-size: 1em">-5</pre>
    <p>Output:</p>
    <pre style="font-size: .5em">VE: Input must...
Finally Block
After Try</pre>
  </div>
</section>
<br>
            <footer class="footline">

            </footer>
          </article>

          </section>
          </section>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="with">With</h1>

<!--
<a href="https://www.youtube.com/watch?v=Mr6OPmyKRCM">YouTube Video</a>
-->
<!--[Video Materials](/10-exceptions/06-python/06-with/video/)-->
<!-- TODO Redo Video so it doesn't close stdin -->
<p>Lastly, Python includes another new statement that is relevant to dealing with exceptions, called the <strong>With</strong> statement.</p>
<h2 id="with">With</h2>
<p>To understand how the <strong>With</strong> statement works in Python, let&rsquo;s look at an example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span><span style="color:#f92672">import</span> traceback
</span></span><span style="display:flex;"><span><span style="color:#f92672">import</span> io
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">if</span> len(sys<span style="color:#f92672">.</span>argv) <span style="color:#f92672">&gt;</span><span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">with</span> open(sys<span style="color:#f92672">.</span>argv[<span style="color:#ae81ff">1</span>]) <span style="color:#66d9ef">as</span> input_file:
</span></span><span style="display:flex;"><span>            data <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;&#34;</span><span style="color:#f92672">.</span>join(input_file<span style="color:#f92672">.</span>readlines())
</span></span><span style="display:flex;"><span>            reader <span style="color:#f92672">=</span> io<span style="color:#f92672">.</span>StringIO(data)
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>        reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin 
</span></span><span style="display:flex;"><span>    
</span></span><span style="display:flex;"><span>    x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>    print(x)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>  
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;ValueError: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e))
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">FileNotFoundError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;FileNotFoundError: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e))</span></span></code></pre></div><p>In this example, we are first using the standard <strong>If</strong> statement to either open a file provided as the first command-line argument, or else we are reading input from the terminal.</p>
<p>If there is a file provided, we open it using a <strong>with</strong> statement.  This statement is used to create a <em>context manager</em> in Python. In short, it allows languages developers to define things that must always be done before and after a resource, such as an open file, is used. In this example, in addition to opening the file, it will make sure the <code>infile</code> is closed when we leave the with block.  The other statements manipulate the file into StringIO object that uses the same methods as sys.stdin.</p>
<p>When the code in the <code>with</code> statement throws an exception, Python will automatically perform the cleanup operations for the resource listed in the <code>with</code>. So, when we are reading input from a file, it would close that file and make sure that it isn&rsquo;t damaged or left open when our program crashes.</p>
<p>In addition, any additional exceptions thrown when trying to close the file are <em>suppressed</em> by the system, so we only see the exception that caused the initial error. This is much better than using a <code>finally</code> statement to close the file, since we&rsquo;d have to run the risk of throwing a second exception inside of the <code>finally</code> statement.</p>
<p>This type of statement is great when writing programs that will handle large amounts of input, either by connecting to a database, reading from a file, or using the Internet to communicate with a server. Many standard Python libraries can be used in this way, especially if they require a <code>close()</code> or other cleanup method to be called when we are finished using them. So, a <code>with</code> statement is a great way to make sure those programs are able to handle exceptions without leaving the system in an unstable state.</p>
<p style="color:red"><b>WARNING:</b> avoid using **with** in conjunction with stdin. <br> `with sys.stdin as reader:` is bad.  Python will dutifully close the stdin at the end of the with-block -- making it unavailable to the program a second time.  This would be like having to close and reopen Word, because every time you hit `return` the keyboard stopped working.</p>
<p>More on <code>with ... as ...:</code> after we cover File input.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of With</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="python-with">Python With</h1>


<a href="https://www.youtube.com/watch?v=Mr6OPmyKRCM">YouTube Video</a>

<h4 id="resources">Resources</h4>
<ul>
<li><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/06-with/video/slides/" target="_blank">Slides</a></li>
</ul>
<h4 id="video-script">Video Script</h4>
<p>One of the most common use cases of the <strong>Try-Except</strong> statement is to deal with input from a file or other resource, mainly because there are many possible exceptions that can occur when reading that input. However, even if we encounter an error, it is also good practice to make sure that we close whatever resource we are using. So, in this program, we have created a reader, initialized it to read input from a file, and then included a <strong>Finally</strong> block that will handle closing the reader, regardless of whether our code reaches an exception or not.</p>
<p>The Python programming language includes another programming construct that we can use to simplify this process, known as a <strong>With</strong> statement. To use a <strong>With</strong> statement, we can simply add the <code>with</code> keyword followed by the variables we&rsquo;d like it to manage and then a colon. So, in this case, we can just add <code>with reader:</code> to our program, and then indent the lines below that use the reader to read input.</p>
<p>Once we do that, we can remove the <strong>Finally</strong> block from our code. This is because the <strong>With</strong> statement will automatically handle closing any open resources used by the <code>reader</code> variable, or any other variable listed after the <code>with</code> keyword.</p>
<p>In addition, if an exception occurs while reading the input, the <strong>With</strong> statement will automatically hide any additional exceptions that are caused when it tries to close the resource. In this way, it is much better than using a <strong>Finally</strong> statement, since the <strong>Finally</strong> statement executes after the exception is handled, and could be the source of additional exceptions that are not caught by the <strong>Try-Except</strong> statement.</p>
<p>Lastly, we can always create new variables from within the <strong>With</strong> statement using the <code>as</code> keyword, as shown here. So, if we know we need to read input from a single source, we can open the file directly inside of the <strong>With</strong> statement.</p>
<p>That&rsquo;s all there is to it! This is a very powerful yet simple way for developers to make sure that resources will be properly closed, no matter what happens.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Python With</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id=""></h1>

<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  x = int(reader.readline())
  print(x)
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
finally:
  reader.close()
</code></pre>
</section>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  <mark>x = int(reader.readline())
  print(x)</mark>
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
finally:
  reader.close()
</code></pre>
</section>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  <mark>x = int(reader.readline())
  print(x)</mark>
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
<mark>finally:
  reader.close()</mark>
</code></pre>
</section>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  <mark>with reader:</mark>
  x = int(reader.readline())
  print(x)
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
finally:
  reader.close()
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  with reader:
  <mark>x = int(reader.readline())
  print(x)</mark>
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
finally:
  reader.close()
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  with reader:
    <mark>x = int(reader.readline())
    print(x)</mark>
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
finally:
  reader.close()
</code></pre>
</section>
<br>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  with reader:
    x = int(reader.readline())
    print(x)
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
<s>finally:
  reader.close()</s>
</code></pre>
</section>
<br>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
  if len(sys.argv) > 1:
    reader = open(sys.argv[1])
  else:
    reader = sys.stdin
<br>
  with reader:
    x = int(reader.readline())
    print(x)
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
</code></pre>
</section>
<br>
<section>
	<pre class="stretch" style="font-size: .61em"><code class="python">import sys
<br>
try:
<br>
  <mark>with open(sys.argv[1]) as reader:</mark>
    x = int(reader.readline())
    print(x)
<br>
except ValueError as e:
  print("ValueError: {}".format(e))
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
</code></pre>
</section>
<br>
            <footer class="footline">

            </footer>
          </article>

          </section>
          </section>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="best-practices">Best Practices</h1>

<p>Now that we&rsquo;ve seen lots of information about how to throw, catch, and handle exceptions in Python, it is a great time to discuss some of the best practices we can apply in our code to make it as readable and bulletproof as possible. While these aren&rsquo;t strict rules that must be followed all the time, they are great things to keep in mind as we write code that deals with exceptions.</p>
<h2 id="leave-no-exception-unhandled">Leave No Exception Unhandled</h2>
<p>As much as possible, we should write our code to handle any exception we can reasonably expect our users to run into when using our programs. We cannot assume that users will always provide the correct input in the correct format, and a single typo by a user should not cause our entire program to crash.</p>
<p>Instead, we should always use <strong>Try-Except</strong> statements whenever possible to detect and handle those errors as simply as possible. In addition, if the program is interactive, we can combine that approach with the use of loops to prompt the user to provide new input to resolve the error.</p>

  
  
<div class="box notices cstyle info">
  <div class="box-label"><i class="fa-fw fas fa-info-circle"></i> Don&rsquo;t Substitute Unchecked Exception Handling for Value Checking</div>
  <div class="box-content">

<p>You can go &ldquo;try except&rdquo; crazy.  Exception handling is powerful, but also slow, really really slow.</p>
<p>You can write something like</p>
<div class="wrap-code highlight"><pre tabindex="0"><code>try:
    ratio = x / y
except ZeroDivisionError as e:
    print(&#34;Cannot divide by zero&#34;)</code></pre></div><p>but</p>
<div class="wrap-code highlight"><pre tabindex="0"><code>if y !=0:
    ratio = x / y;
else:
    print(&#34;Cannot divide by zero&#34;)</code></pre></div><p>executes a lot more efficiently.</p>
<p>Many exceptions can be avoided through value checking.  In this course, we may direct you to throw and catch exceptions of this type for practice in exception coding.</p>
</div>
</div>
<p>The <a href="https://docs.python.org/3/" target="_blank">Python Documentation</a>
 is an okay resource to determine which exceptions could be thrown by any methods used in our code.  However Python does not provide a standard or comprehensive list of the Exceptions and conditions which cause them for all methods in all modules&ndash;nor is their enumeration in the Python Docs in a standard place or format.</p>
<h2 id="dp-not-use-exception-handling-for-control-flow">Dp Not Use Exception Handling for Control Flow</h2>
<p>You might be tempted to do something like this</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> open(sys<span style="color:#f92672">.</span>argv[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">Exception</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin </span></span></code></pre></div><p>Where if there is any problem accessing sys.argv[1] as a file, such as it was not provided or it does not exist, you just use the keyboard.  Here you are letting an exception control what is happening without telling the user there was a problem.   Better would be</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">if</span> len(sys<span style="color:#f92672">.</span>argv) <span style="color:#f92672">&gt;</span> <span style="color:#ae81ff">1</span>:
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>        reader<span style="color:#f92672">=</span> open(sys<span style="color:#f92672">.</span>arv[<span style="color:#ae81ff">1</span>])
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">except</span> <span style="color:#a6e22e">OSError</span>:
</span></span><span style="display:flex;"><span>        print (<span style="color:#e6db74">&#34;there was a problem accessing </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">, please check the file and try again&#34;</span><span style="color:#f92672">.</span>format(sys<span style="color:#f92672">.</span>argv[<span style="color:#ae81ff">1</span>]))
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">return</span> <span style="color:#75715e"># here we assume this will exit the program</span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>    reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin</span></span></code></pre></div><p>Programmers do not expect control flow decisions to be made <b>in</b> exception-handlers.  It makes analysis of the program very difficult.</p>
<h2 id="be-specific">Be Specific</h2>
<p>We should also always strive to use specific exceptions in our <code>except</code> statements whenever we can. So, if we are opening a file, we should include an <code>except</code> statement for a FileNotFoundError, and not just a single generic <code>Exception</code>. Even though this means we may have to include several <code>except</code> statements, it is much better in the long run because it allows us to know exactly what happened when our code has a problem.</p>
<p>In addition, we should always make sure we catch the most specific exceptions first, before any more generic exceptions. As we saw earlier, if we try to catch an OSError before a FileNotFoundError, we won&rsquo;t be able to tell when we&rsquo;ve reached a FileNotFoundError at all, since it is a subtype of the OSError.</p>
<h2 id="use-messages-and-stack-traces">Use Messages and Stack Traces</h2>
<p>The Python Exception class includes some very helpful methods we can use to get additional information when we encounter an exception.</p>
<p>Here&rsquo;s an example to show what we can learn:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span><span style="color:#f92672">import</span> traceback
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span> <span style="color:#f92672">/</span> <span style="color:#ae81ff">0</span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ZeroDivisionError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error! Trying to Divide by Zero!&#34;</span>)
</span></span><span style="display:flex;"><span>  traceback<span style="color:#f92672">.</span>print_exc(file<span style="color:#f92672">=</span>sys<span style="color:#f92672">.</span>stdout)</span></span></code></pre></div><p>When this code is executed, it will produce the following output:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span><span style="color:#e6db74">$</span> python<span style="color:#ae81ff">3</span> <span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>StackTrace.py
</span></span><span style="display:flex;"><span>Error<span style="color:#f92672">!</span> Trying to Divide by Zero<span style="color:#f92672">!</span>
</span></span><span style="display:flex;"><span>Traceback <span style="color:#f92672">(</span>most recent call last<span style="color:#f92672">)</span>:
</span></span><span style="display:flex;"><span>  File &#34;<span style="color:#ae81ff">8</span>p<span style="color:#f92672">-</span>except<span style="color:#f92672">/</span>StackTrace.py&#34;, line <span style="color:#ae81ff">5</span>, in &lt;module&gt;
</span></span><span style="display:flex;"><span>    x <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span> <span style="color:#f92672">/</span> <span style="color:#ae81ff">0</span>
</span></span><span style="display:flex;"><span>ZeroDivisionError: division by zero</span></span></code></pre></div><p>On the first line, we are printing our own error message. Below that, we are using <code>traceback.print_exc(file=sys.stdout)</code> to print a full stack trace showing the location of the error in code. In this example, we included <code>file=sys.stdout</code> because the method will print to <code>sys.stderr</code> by default, a different output stream. This just makes it easier to see all of our output on the terminal for now.</p>
<p>In general, it is best to only show a short error message to users, but in some cases it may be better to add our own message. The text &ldquo;division by zero&rdquo; isn&rsquo;t very clear, even to developers. Instead, we could say &ldquo;Error: divisor cannot be zero&rdquo; to make the error message clearer.</p>
<p>The information contained in the stack trace is very helpful to developers when trying to debug and fix problems in the code, but that information is very confusing to users. As we learn how to build more advanced programs, we&rsquo;ll see how to record and log those error messages and stack traces for debugging, but hide them from our users.</p>
<p>To see what other methods are available, refer to the <a href="https://docs.python.org/3/library/traceback.html" target="_blank">Traceback</a>
 library in the Python documentation.</p>
<h2 id="dont-ignore-exceptions">Don&rsquo;t Ignore Exceptions</h2>
<p>Another big problem is that many developers tend to catch exceptions, only to ignore them so their program doesn&rsquo;t crash. Here&rsquo;s a quick example:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">0</span>
</span></span><span style="display:flex;"><span>reader <span style="color:#f92672">=</span> sys<span style="color:#f92672">.</span>stdin
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">Exception</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">pass</span>
</span></span><span style="display:flex;"><span>  <span style="color:#75715e"># do nothing</span></span></span></code></pre></div><p>In this code, if the user inputs something that can&rsquo;t be converted to an integer, the code just silently ignores the exception and proceeds with <code>x</code> still storing the value $0$. While that may not cause issues, it can also make it very frustrating to debug later issues or changes in this program. So, it is always best to output an error message when an exception occurs, even if it can be easily ignored without additional input from the user. This will make it easier to debug additional issues later on in development.</p>
<h2 id="bulletproof-code">Bulletproof Code</h2>
<p>Here&rsquo;s a simple program that asks the user for input, and will repeat the question until a valid input is received. This code is designed to handle many common situations and exceptions:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> sys
</span></span><span style="display:flex;"><span><span style="color:#f92672">import</span> traceback
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">0</span>
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">with</span> open(sys<span style="color:#f92672">.</span>argv[<span style="color:#ae81ff">1</span>]) <span style="color:#66d9ef">as</span> reader:
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">while</span> x <span style="color:#f92672">&lt;=</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>      <span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>        x <span style="color:#f92672">=</span> int(reader<span style="color:#f92672">.</span>readline())
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&lt;=</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>          print(<span style="color:#e6db74">&#34;Error: Negative Integer Detected!&#34;</span>)
</span></span><span style="display:flex;"><span>      <span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>        print(<span style="color:#e6db74">&#34;Error: Integer Not Found!&#34;</span>)
</span></span><span style="display:flex;"><span>      <span style="color:#66d9ef">except</span> <span style="color:#a6e22e">Exception</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>        print(<span style="color:#e6db74">&#34;Error: Unknown Input Error&#34;</span>)
</span></span><span style="display:flex;"><span>        sys<span style="color:#f92672">.</span>exit() <span style="color:#75715e"># probably can&#39;t recover, so stop executing</span>
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;the file contained </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(x))
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">FileNotFoundError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: Unable to File Open Reader!&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">Exception</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>  print(<span style="color:#e6db74">&#34;Error: Unable to File Open Reader!&#34;</span>)</span></span></code></pre></div><p>There are several items in this code that help make it very bulletproof:</p>
<ol>
<li>First, the program uses a <strong>Try-Except</strong> statement containing a <strong>With</strong> statement to make sure that the file will be properly closed when we are done with it. As we&rsquo;ve discussed, this is a good practice when handling input via files, but really any input object can be handled in this way.</li>
<li>The outer <strong>Try-Except</strong> statement has a two <code>except</code> blocks.  The first handles not finding the file (the most likely exception).  The second captures anything else that might go wrong with the reader .</li>
<li>Inside of the <strong>While</strong> loop, there is a second <strong>Try-Except</strong> statement to handle errors that come from reading an individual input, such as a ValueError.</li>
<li>In addition, that inner <strong>Try-Except</strong> statement will also catch any generic Exceptions that might occur when reading input. In that case, we use the <code>sys.exit()</code> method to stop executing the program, since it may be difficult to continue to read input in that case. Thankfully, since we are using a <strong>With</strong> block, the reader will be correctly closed for us automatically. In addition, any <code>finally</code> blocks would be executed before the program stops.</li>
</ol>

  
  
<div class="box notices cstyle warning">
  <div class="box-label"><i class="fa-fw fas fa-exclamation-triangle"></i> Don&rsquo;t Exit Early!</div>
  <div class="box-content">

<p>We have not discussed the <code>sys.exit()</code> method yet, but you may have come across it while reading code online. In Python, the <code>sys.exit()</code> method is used to exit the Python interpreter safely from within a program</p>
<p>For now, if we find that we need to exit our program when handling an error, we can safely use the <code>sys.exit()</code> method as shown in the example above. It will make sure that any <code>finally</code> blocks and <strong>With</strong> statements are executed properly.</p>
<p>There are some other ways to exit the Python interpreter that you can find online, but they may do so without properly closing any resources or executing <code>finally</code> blocks. They can also make your code much more difficult to maintain and test. This can be very dangerous!</p>
</div>
</div>
<p>Of course, there are many things that can be done differently in this code, depending on our preferences and how we&rsquo;d like our program to function. This is just one possible way to build useful code that handles several exceptions.</p>

            <footer class="footline">

            </footer>
          </article>

    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="a-worked-example">A Worked Example</h1>

<!--
<a href="https://www.youtube.com/watch?v=XaDEahMnjgU">YouTube Video</a>
-->
<!--[Video Materials](/10-exceptions/06-python/08-example/video/)-->
<!-- TODO Redo Video -->
<p>Let&rsquo;s work through an entire example program together to see how we can build programs that handle exceptions quickly and easily, without allowing the program to crash when invalid input is received.</p>
<h2 id="problem-statement">Problem Statement</h2>
<p>Consider the following problem statement for a driver-class program <code>Example.py</code>:</p>
<blockquote>
<p>Write a program to accept a list of numbers, one per line from the terminal.</p>
</blockquote>
<blockquote>
<p>The numbers can either be whole numbers or floating point numbers. The program should continue to accept input until a number equal to $0$ is input, or a blank line is received. Of course, if the input in a file ends before a $0$, that can be treated as the end of the input.</p>
</blockquote>
<blockquote>
<p>Once $0$ is received or the input ends, the program should print the largest and smallest number provided as input (not including the $0$ to end input). Sample outputs are shown below.</p>
</blockquote>
<blockquote>
<p>The program should catch and handle all common exceptions. When an exception is caught, the program should print the name of the exception, followed by the message included in the exception. It should then continue to accept input (if possible).</p>
</blockquote>
<h2 id="sample-inputs--outputs">Sample Inputs &amp; Outputs</h2>
<p>Here&rsquo;s an example of an expected input for the program:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span>5.0
</span></span><span style="display:flex;"><span>3
</span></span><span style="display:flex;"><span>8.5
</span></span><span style="display:flex;"><span>7
</span></span><span style="display:flex;"><span>k
</span></span><span style="display:flex;"><span>2.3.6
</span></span><span style="display:flex;"><span>0.0</span></span></code></pre></div><p>Here is the correct output for that input:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-tex" data-lang="tex"><span style="display:flex;"><span>ValueError: could not convert string to float: &#39;k&#39;
</span></span><span style="display:flex;"><span>ValueError: could not convert string to float: &#39;2.3.6&#39;
</span></span><span style="display:flex;"><span>Maximum: 8.5
</span></span><span style="display:flex;"><span>Minimum: 3.0</span></span></code></pre></div><p>Pause a moment to think about control flow, loops and exceptions you might need to handle.</p>
<p>When first starting out in coding and exception handling, it is often best to first write the code <strong>without</strong> exception handling, test it, then add the exception stuff.  Exception handlers can hide logic errors.</p>
<h2 id="handle-input">Handle Input</h2>
<p>First, we can write code to handle user input. The problem statement tells us to read inputs, one per line, until the user inputs 0. We also know that the user can input either whole numbers or floating point numbers. So, to make it simple, we&rsquo;ll just use floating point numbers for everything&ndash; this will require us to import math for number comparisons.  Now, math.isclose() cannot handle None, so instead we&rsquo;ll need to pick an initial value for our loop condition variable that will allow us to enter the loop, i.e. make the loop condition <code>True</code>.</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">1.0</span>  <span style="color:#75715e"># math.isclose() cannot handle None, wo instead we pick an initial value for x </span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">while</span> <span style="color:#f92672">not</span> math<span style="color:#f92672">.</span>isclose(x,<span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>  string <span style="color:#f92672">=</span> reader<span style="color:#f92672">.</span>readline()
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">if</span> len(string) <span style="color:#f92672">==</span> <span style="color:#ae81ff">0</span>: 
</span></span><span style="display:flex;"><span>    x <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.0</span>
</span></span><span style="display:flex;"><span>  <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>    x <span style="color:#f92672">=</span> float(string)</span></span></code></pre></div><p>If there is a a blank line, the <code>strip()</code> method will return the empty string.  Our program should take the the same action as if seeing a 0.0 so we assign 0.0 to x.  You should at this point test your logic , then add exception handlers.  Here we know that if <code>string</code> cannot convert until we&rsquo;ll get a ValueError.</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">1.0</span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">while</span> <span style="color:#f92672">not</span> math<span style="color:#f92672">.</span>isclose(x, <span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>        string <span style="color:#f92672">=</span> reader<span style="color:#f92672">.</span>readline()<span style="color:#f92672">.</span>strip()
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">if</span> len(string) <span style="color:#f92672">==</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>            x <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.0</span>
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>            x <span style="color:#f92672">=</span> float(string)
</span></span><span style="display:flex;"><span>            <span style="color:#66d9ef">if</span> <span style="color:#f92672">not</span> math<span style="color:#f92672">.</span>isclose(x, <span style="color:#ae81ff">0.0</span>):  
</span></span><span style="display:flex;"><span>                <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&lt;</span> minimum <span style="color:#f92672">or</span> math<span style="color:#f92672">.</span>isclose(minimum, <span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>                    minimum <span style="color:#f92672">=</span> x
</span></span><span style="display:flex;"><span>                <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&gt;</span> maximum <span style="color:#f92672">or</span> math<span style="color:#f92672">.</span>isclose(maximum, <span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>                    maximum <span style="color:#f92672">=</span> x
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>        print(<span style="color:#e6db74">&#34;ValueError: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e))</span></span></code></pre></div><p>This should handle most exceptions that will occur in this program. Of course, there are many other ways that this code could be structured as well.</p>
<h2 id="logic">Logic</h2>
<p>Once we have the code to handle input, we can write the code to deal with logic. Keeping track of the minimum and maximum of a set of inputs is pretty simple:</p>
<div class="wrap-code highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span>maximum <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.0</span>
</span></span><span style="display:flex;"><span>minimum <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.0</span>
</span></span><span style="display:flex;"><span>x <span style="color:#f92672">=</span> <span style="color:#ae81ff">1.0</span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">while</span> <span style="color:#f92672">not</span> math<span style="color:#f92672">.</span>isclose(x, <span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>        string <span style="color:#f92672">=</span> reader<span style="color:#f92672">.</span>readline()<span style="color:#f92672">.</span>strip()
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">if</span> len(string) <span style="color:#f92672">==</span> <span style="color:#ae81ff">0</span>:
</span></span><span style="display:flex;"><span>            x <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.0</span>
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">else</span>:
</span></span><span style="display:flex;"><span>            x <span style="color:#f92672">=</span> float(string)
</span></span><span style="display:flex;"><span>            <span style="color:#66d9ef">if</span> <span style="color:#f92672">not</span> math<span style="color:#f92672">.</span>isclose(x, <span style="color:#ae81ff">0.0</span>):  
</span></span><span style="display:flex;"><span>                <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&lt;</span> minimum <span style="color:#f92672">or</span> math<span style="color:#f92672">.</span>isclose(minimum, <span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>                    minimum <span style="color:#f92672">=</span> x
</span></span><span style="display:flex;"><span>                <span style="color:#66d9ef">if</span> x <span style="color:#f92672">&gt;</span> maximum <span style="color:#f92672">or</span> math<span style="color:#f92672">.</span>isclose(maximum, <span style="color:#ae81ff">0.0</span>):
</span></span><span style="display:flex;"><span>                    maximum <span style="color:#f92672">=</span> x
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span> <span style="color:#66d9ef">as</span> e:
</span></span><span style="display:flex;"><span>        print(<span style="color:#e6db74">&#34;ValueError: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e))
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>    
</span></span><span style="display:flex;"><span>print(<span style="color:#e6db74">&#34;Maximum: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(maximum))
</span></span><span style="display:flex;"><span>print(<span style="color:#e6db74">&#34;Minimum: </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(minimum))</span></span></code></pre></div><p>We can simply create variables to track the minimum and maximum values. Since our program won&rsquo;t accept $0$ as an input, we can use that as the default value for these variables.  Our logic does not use any functions likely to throw new errors, so no more exception handling is required.</p>
<h2 id="testing">Testing</h2>
<p>Finally, we may want to do some quick testing of our program. In theory, it should handle any inputs provided, including files that don&rsquo;t exist as command-line arguments and more. When testing, we should always see if we can find some input that breaks our program, then adjust the program as needed to prevent that problem. Of course, we should always make sure that it produces the correct answers, too.</p>

  
    
    
  
  
<div class="box notices cstyle noiframe">
  <div class="box-label"><i class="fa-fw fas fa-times-circle"></i> Web Only</div>
  <div class="box-content">

<p>This content is presented in the course directly through Codio. Any references to interactive portions are only relevant for that interface. This content is included here as reference only.</p>
</div>
</div>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of A Worked Example</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id="python-example">Python Example</h1>


<a href="https://www.youtube.com/watch?v=XaDEahMnjgU">YouTube Video</a>

<h4 id="resources">Resources</h4>
<ul>
<li><a href="https://ksu-cs-textbooks.github.io/cc210/10-exceptions/06-python/08-example/video/slides/" target="_blank">Slides</a></li>
</ul>
<h4 id="video-script">Video Script</h4>
<p>Now that we&rsquo;ve learned about how to catch and handle exceptions in our programs, let&rsquo;s work on creating a full example program to see how working with exceptions affects our thought process when developing code.</p>
<p>As always, here is our problem statement&hellip;</p>
<p>Zoinks! That&rsquo;s a pretty complex problem statement. So, let&rsquo;s break it down into smaller parts and see how we can implement each part individually.</p>
<p>First, we&rsquo;ll need to handle user input. Previously in this textbook, we would simply use the skeleton code provided in earlier chapters. However, now that we understand how to work with exceptions, we can improve and simplify that skeleton code a bit. So, let&rsquo;s look at that first.</p>
<p>First, we&rsquo;ll need to import the <code>sys</code> module. Then, we can create a reader by trying to open a file provided as the first command-line argument. Let&rsquo;s just assume that the user has provided a valid file for now. We&rsquo;ll see later how we can use our exception handlers to deal with the cases where the user has provided no file or an invalid file.</p>
<p>Since we are opening a file, we know that this could cause the FileNotFoundError, So, we&rsquo;ll need to use a <strong>Try-Except</strong> statement and add an exception handler to deal with that exception.</p>
<p>When we catch that exception, we know that the user has provided an invalid file. In that case, we can just use the terminal as our input, so we&rsquo;ll add a line of code to the exception handler to do just that.</p>
<p>In addition, since we are reading from an list, there is a chance that we could run into an IndexError, especially if we don&rsquo;t check the size of the list first. So, we can add one more exception handler to deal with that issue. Again, since the user didn&rsquo;t provide a file as a command-line input, we can just read input from the terminal instead.</p>
<p>That&rsquo;s all the code we need to initialize our reader to read either from a file, if a valid file is provided, or the terminal if not. Once we&rsquo;ve done that, we can use a <strong>With</strong> statement to actually handle reading the input.</p>
<p>There we go! We&rsquo;ve now created a new version of our skeleton code that does a great job of catching and handling lots of common exceptions. For the rest of this program, we&rsquo;ll build the logic and place it where I&rsquo;ve highlighted this comment in the code.</p>
<p>So, let&rsquo;s dig into the actual problem statement and build our program. First, we know that we are reading a list of numbers from an input file. So, we can use a simple <strong>While</strong> loop to handle this. Next, we&rsquo;ll see that the problem statement tells us that we could find either integers or floating-point numbers. Thankfully, we can store both of those in a double data type, so we can just use the <code>float()</code> method to convert input to the correct data type. Additionally, the problem statement tells us to stop reading input when we read a line that contains a value equal to 0, so we can add a simple <strong>If-Then</strong> statement to deal with that situation.</p>
<p>Now we need to start thinking about exceptions again. If we look at our code so far, we&rsquo;ll see that we are converting the input we read to a floating-point number. That could cause an ValueError if the input can&rsquo;t be converted to that data type. So, we&rsquo;ll need to surround this code in a <strong>Try-Except</strong> statement, and add an exception handler to the bottom to handle that exception. We should also realize that reading input from a file using a <strong>While</strong> loop could raise an EOFError when we try and read more data after reaching the end of a file. However, when reading from the terminal, that may cause us to read an empty line if we run out of input. To deal with that, we&rsquo;ll raise a new EOFError there as well, and then add another exception handler for that exception. In that handler, we&rsquo;ll add a <code>break</code> statement, since we know we&rsquo;ve run out of input to read.</p>
<p>There we go! From here, we just need to add the program logic to keep track of the minimum and maximum values. So, we&rsquo;ll declare two variables before the <strong>While</strong> loop, then use two <strong>If-Then</strong> statements inside of the loop to update them. Since our program will not allow the user to input the value <code>0</code>, we can use those values as our defaults for both the minimum and maximum. Otherwise, we&rsquo;d have to use a different method to update those values.</p>
<p>Finally, we&rsquo;ll add two more print statements after the <strong>While</strong> loop to print the output.</p>
<p>That&rsquo;s all there is to it! As we can see, even though the problem statement is a bit complex, the actual logic for the problem is simple. In addition, by catching and handling several common exceptions, it actually can make our code more straightforward, since we don&rsquo;t need a bunch of <strong>If-Then</strong> statements to validate input before using it. Instead, we can just assume that it works, and if it doesn&rsquo;t we&rsquo;ll use exception handlers to get our program back on track.</p>

            <footer class="footline">

            </footer>
          </article>

          <section>
            <h1 class="a11y-only">Subsections of Python Example</h1>
    
    
          <article class="default">
            <header class="headline">
            </header>
<h1 id=""></h1>

<br>
<section>
	<h2>Problem Statement</h2>
</section>
<section>
	<p style="font-size: 0.5em">Write a program to accept a list of numbers, one per line. Input is provided from a file if one is provided as the first command line argument. If a file is not provided, input should be read from the terminal.</p>
	<p style="font-size: 0.5em">The numbers can either be whole numbers or floating point numbers. The program should continue to accept input until a number equal to 0 is input. Of course, if the input in a file ends before a 0, that can be treated as the end of the input.</p>
	<p style="font-size: 0.5em">Once 0  is received or the input ends, the program should print the largest and smallest number provided as input (not including the 0 to end input). Sample outputs are shown below.</p>
	<p style="font-size: 0.5em">The program should catch and handle all common exceptions. When an exception is caught, the program should print the name of the exception, followed by the message included in the exception. It should then continue to accept input (if possible). Specifically, if it is unable to open the file provided, input should be read from the terminal.</p>
</section>
<section>
  <h2>Zoinks!</h2>
	<img class="stretch plain" src="https://ksu-cs-textbooks.github.io/cc210/images/zoinks.gif">
  <p class="imagecredit">Image Credit: <a href="https://giphy.com/gifs/5hdg7p9NE7VlLWaeRK">Boomerang via Giphy</a></p>
	<p>Let's break it down into smaller parts</p>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
reader = open(sys.argv[1])
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
reader = <mark>open(sys.argv[1])</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
<mark>try:</mark>
  reader = open(sys.argv[1])
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
<mark>try:</mark>
  reader = open(sys.argv[1])
<mark>except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
try:
  reader = open(sys.argv[1])
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
  <mark>reader = sys.stdin</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
try:
  reader = open(<mark>sys.argv[1]</mark>)
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
  reader = sys.stdin
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
try:
  reader = open(<mark>sys.argv[1]</mark>)
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
  reader = sys.stdin
<mark>except IndexError as e:
  print("IndexError: {}".format(e))
  reader = sys.stdin</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
try:
  reader = open(sys.argv[1])
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
  reader = sys.stdin
except IndexError as e:
  print("IndexError: {}".format(e))
  reader = sys.stdin
<br>
<mark>with reader:</mark>
<br>
  # more code here
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">import sys
<br>
try:
  reader = open(sys.argv[1])
except FileNotFoundError as e:
  print("FileNotFoundError: {}".format(e))
  reader = sys.stdin
except IndexError as e:
  print("IndexError: {}".format(e))
  reader = sys.stdin
<br>
with reader:
<br>
  <mark># more code here<mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Input is provided from a file [or] read from the terminal.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  string = reader.readline().strip()
  if len(string) == 0:
    raise EOFError("Unexpected End of Input!")
  input = float(string)
  if input == 0.0:
    break
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  string = reader.readline().strip()
  if len(string) == 0:
    raise EOFError("Unexpected End of Input!")
  input = <mark>float(string)</mark>
  if input == 0.0:
    break
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... <mark>whole numbers or floating point numbers</mark>... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  string = reader.readline().strip()
  if len(string) == 0:
    raise EOFError("Unexpected End of Input!")
  input = float(string)
  <mark>if input == 0.0:
    break</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... <mark>accept input until a number equal to 0 is input.</mark></p>
    <p style="font-size: .7em">The program should catch and handle all common exceptions.</p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  string = reader.readline().strip()
  if len(string) == 0:
    raise EOFError("Unexpected End of Input!")
  input = <mark>float(string)</mark>
  if input == 0.0:
    break
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em"><mark>The program should catch and handle all common exceptions.</mark></p>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  <mark>try:</mark>
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = float(string)
    if input == 0.0:
      break
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em"><mark>The program should catch and handle all common exceptions.</mark></p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = <mark>float(string)</mark>
    if input == 0.0:
      break
  <mark>except ValueError as e:
    print("ValueError: {}".format(e))</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em"><mark>The program should catch and handle all common exceptions.</mark></p>
  </div>
</section>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      <mark>raise EOFError("Unexpected End of Input!")</mark>
    input = float(string)
    if input == 0.0:
      break
  except ValueError as e:
    print("ValueError: {}".format(e))
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em"><mark>The program should catch and handle all common exceptions.</mark></p>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      <mark>raise EOFError("Unexpected End of Input!")</mark>
    input = float(string)
    if input == 0.0:
      break
  except ValueError as e:
    print("ValueError: {}".format(e))
  <mark>except EOFError as e:
    print("EOFError: {}".format(e))
    break # out of input, so we should stop there</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">list of numbers, one per line... whole numbers or floating point numbers... accept input until a number equal to 0 is input.</p>
    <p style="font-size: .7em"><mark>The program should catch and handle all common exceptions.</mark></p>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = float(string)
    if input == 0.0:
      break
  except ValueError as e:
    print("ValueError: {}".format(e))
  except EOFError as e:
    print("EOFError: {}".format(e))
    break # out of input, so we should stop there
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Once 0 is received or the input ends, the program should print the largest and smallest number provided as input (not including the 0 to end input).</p>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python"><mark>maximum = 0.0
minimum = 0.0</mark>
<br>
while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = float(string)
    if input == 0.0:
      break
  except ValueError as e:
    print("ValueError: {}".format(e))
  except EOFError as e:
    print("EOFError: {}".format(e))
    break # out of input, so we should stop there
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Once 0 is received or the input ends, the program should print the largest and smallest number provided as input (not including the 0 to end input).</p>
  </div>
</section>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python"><mark>maximum = 0.0
minimum = 0.0</mark>
<br>
while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = float(string)
    if input == 0.0:
      break
<br>
    <mark>if input &lt; minimum or minimum == 0.0:
      minimum = input
    if input > maximum or maximum == 0.0:
      maximum = input</mark>
<br>
  except ValueError as e:
    print("ValueError: {}".format(e))
  except EOFError as e:
    print("EOFError: {}".format(e))
    break # out of input, so we should stop there
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Once 0 is received or the input ends, the program should print the largest and smallest number provided as input (not including the 0 to end input).</p>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python"><mark>maximum = 0.0
minimum = 0.0</mark>
<br>
while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = float(string)
    if input == 0.0:
      break
<br>
    <mark>if input &lt; minimum or minimum == 0.0:
      minimum = input
    if input > maximum or maximum == 0.0:
      maximum = input</mark>
<br>
  except ValueError as e:
    print("ValueError: {}".format(e))
  except EOFError as e:
    print("EOFError: {}".format(e))
    break # out of input, so we should stop there
<br>
<mark>print("Maximum: {}".format(maximum))
print("Minimum: {}".format(minimum))</mark>
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Once 0 is received or the input ends, the program should print the largest and smallest number provided as input (not including the 0 to end input).</p>
  </div>
</section>
<br>
<br>
<br>
<section>
  <div style="float: right; width: 70%">
    <pre class="stretch" style="font-size: .37em"><code class="python">maximum = 0.0
minimum = 0.0
<br>
while True:
  try:
    string = reader.readline().strip()
    if len(string) == 0:
      raise EOFError("Unexpected End of Input!")
    input = float(string)
    if input == 0.0:
      break
<br>
    if input &lt; minimum or minimum == 0.0:
      minimum = input
    if input > maximum or maximum == 0.0:
      maximum = input
<br>
  except ValueError as e:
    print("ValueError: {}".format(e))
  except EOFError as e:
    print("EOFError: {}".format(e))
    break # out of input, so we should stop there
<br>
print("Maximum: {}".format(maximum))
print("Minimum: {}".format(minimum))
</code></pre>
  </div>
  <div style="width: 30%">
    <p style="font-size: .7em">Once 0 is received or the input ends, the program should print the largest and smallest number provided as input (not including the 0 to end input).</p>
  </div>
</section>
<br>
            <footer class="footline">

            </footer>
          </article>

          </section>
          </section>
          </section>

        </div>
      </main>
    
<div class="git-footer">
<p class="theme-version-footer">5.18.0</p>
<p>Last modified by: 
            <i class='fas fa-user'></i> Russell Feldhausen
            <i class='fas fa-calendar'></i> <a href="https://gitlab.cs.ksu.edu/cc/210/generic/textbook/-/commit/063dfde2152a295ed6dbac3b66d864d5a5d4d566">Aug 11, 2023</a>
</p>
</div>

    
    </div>
    <script src="https://ksu-cs-textbooks.github.io/cc210/js/clipboard.min.js?1691776799" defer></script>
    <script src="https://ksu-cs-textbooks.github.io/cc210/js/perfect-scrollbar.min.js?1691776799" defer></script>
    <script src="https://ksu-cs-textbooks.github.io/cc210/js/theme.js?1691776799" defer></script>
  </body>
</html>
